[tasks.default]
clear = true
dependencies = [
    "add-target",
    "install-flip-link",
    "examples-compile",
    "clippy",
    "check-format",
]

[tasks.install-flip-link]
command = "cargo"
args = ["install", "flip-link"]

[tasks.add-target]
command = "rustup"
args = ["target", "add", "thumbv7m-none-eabi"]
