[package]
name = "microflow"
version = "0.1.0"
edition = "2021"

[dependencies]
microflow-macros = { version = "0.1", path = "microflow-macros" }
nalgebra = { version = "0.32", default-features = false, features = ["macros"] }
simba = { version = "0.8", default-features = false }
libm = "0.2"
num-traits = { version = "0.2", default-features = false }

[dev-dependencies]
csv = "1.2"

[workspace]
members = ["microflow-macros"]
exclude = ["examples"]

[patch.crates-io]
nalgebra = { git = "https://github.com/matteocarnelos/nalgebra" }
