[target.'cfg(target_arch = "avr")']
runner = "arduino-run -b arduino:avr:uno"
rustflags = [
    "-C", "default-linker-libraries",
    "-C", "link-arg=-Wl,--allow-multiple-definition",
]

[build]
target = "avr-unknown-gnu-atmega328"

[unstable]
build-std = ["core"]
