[target.'cfg(target_arch = "avr")']
runner = "ravedude uno -cb 57600 -P /dev/cu.wchusbserial14420"
rustflags = [
    "-C", "default-linker-libraries",
]

[build]
target = "avr-unknown-gnu-atmega328"

[unstable]
build-std = ["core"]
