[target.'cfg(target_arch = "avr")']
runner = "ravedude nano -cb 57600"
rustflags = [
    "-C", "default-linker-libraries",
]

[build]
target = "avr-unknown-gnu-atmega328"

[unstable]
build-std = ["core"]
