[target.'cfg(target_arch = "xtensa")']
runner = "espflash --monitor"
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
    "-C", "link-arg=-nostartfiles",
]

[build]
target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core"]
