name: Cargo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CLICOLOR_FORCE: 1
  CARGO_TERM_COLOR: always

jobs:
  make:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Crates
      run: cargo install cargo-make flip-link espup
    - name: Install Nightly Toolchain
      run: rustup toolchain install nightly --component rust-src
    - name: Install ESP Toolchain
      run: espup install
    - name: Install AVR Toolchain
      run: sudo apt install -y avr-libc gcc-avr pkg-config
    - name: Add Rust Targets
      run: rustup target add thumbv7em-none-eabihf thumbv7m-none-eabi
    - name: Make All
      run: |
        . ~/export-esp.sh
        cargo make all
